### ISSUE TITLE
migration 2.0.3 -> 2.0.5 issue

### ISSUE THREAD

**Issue by redDwarf03** [turkialawlqy/string_encryption#1]
Hello

first, thank you for your lib.
I don't understand something: I change the version of the lib in my project to version 2.0.5 and since, the use of object:  PlatformStringCryptor doesn't work.
Have you change something ? 
Thx

**Comment by itsMarcoSolis** [comment]
Looks like you now have to use StringEncryption instead of PlatformStringCryptor.

**Comment by redDwarf03** [comment]
Yes in theory but the 2.0.5 doesn’t work

**Comment by turkialawlqy** [comment]
> Yes in theory but the 2.0.5 doesn’t work

please upload screen shot for error

**Comment by redDwarf03** [comment]
<img width="1055" alt="Capture d’écran 2021-10-06 à 14 39 11" src="https://user-images.githubusercontent.com/68340133/136203983-0c708d1b-3c73-4a6b-b3e8-7e4d2d301e58.png">
<img width="413" alt="Capture d’écran 2021-10-06 à 14 37 10" src="https://user-images.githubusercontent.com/68340133/136203993-512535c1-7395-4112-8dd7-7041489e8628.png">
<img width="556" alt="Capture d’écran 2021-10-06 à 14 36 52" src="https://user-images.githubusercontent.com/68340133/136203998-f84fb7e2-f01c-4019-b404-bd0a0e6b748c.png">

**Comment by redDwarf03** [comment]
hello @turkialawlqy . any idea about my issue please ?
